### PR TITLE
docs: (sum plugin) fix manifest example

### PR DESCRIPTION
**Pull request by jrgtt**
### Types of changes

- [ ] Enhancement (project structure, spelling, grammar, formatting)
- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [x] I have updated the documentation accordingly.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

### A description of the changes proposed in the Pull Request
Running the manifest example as-is doesn't work as expected. It misses a `compute` key under the pipeline config.

### CODE REVIEW

**Comment by jrgtt** [comment]
Hello everyone, first time here, hope it's okay to create this PR out of the blue. I was toying with the Sum plugin but noticed that the documented example doesn't really compute the expected `energy` value due to a missing `compute` statement.

**Comment by jmcook1186** [comment]
Hi @jrgtt thank you for contributing, and good catch.
This can be merged, but first you need to sign your commits to satisfy our DCO.
Cheers

**Comment by jmcook1186** [comment]
Also, @jrgtt  please note that this repo is not actively maintained any more - these plugins have migrated to our IF repository (https://github.com/Green-Software-Foundation/if) and now come bundled in with Impact Framework instead of being a separate package.

**Comment by jrgtt** [comment]
@jmcook1186 oops my bad, I guess reading the main README would have been helpful 😅

I will close this PR

**Pull request closed without merging**
